paths:
  /api/products:
    get:
      summary: Obtener el listado de todos los productos
      tags:
        - products
      parameters:
        - name: cookie
          in: header
          required: true
          description: JWT Cookie para autenticación
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Todos los productos fueron obtenidos satisfactoriamente de la DB.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/products"
        "500":
          description: Error interno del servidor, generalmente causado por una query defectuosa o fallo en la conexión.
    post:
      summary: Crear un nuevo producto
      tags:
        - products
      parameters:
        - name: cookie
          in: header
          required: true
          description: JWT Cookie para autenticación
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/products"
        "500":
          description: Error interno del servidor, generalmente causado por una query defectuosa o fallo en la conexión.
  /api/products/{pid}:
    get:
      summary: Obtener un producto por pid (identificador del producto ObjectId)
      tags:
        - products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto a buscar
          schema:
            type: string
        - name: cookie
          in: header
          required: true
          description: JWT Cookie para autenticación
          schema:
            type: string
      responses:
        "200":
          description: producto obtenido correctamente de nuestra DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/products"
        "404":
          description: Producto no encontrado en la DB
        "500":
          description: Error interno del servidor, generalmente causado por una query defectuosa o fallo en la conexión.
    put:
      summary: Actualiza un producto por segun el pid (identificador del producto ObjectId)
      tags:
        - products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto a buscar
          schema:
            type: string
        - name: cookie
          in: header
          required: true
          description: JWT Cookie para autenticación
          schema:
            type: string
      responses:
        "200":
          description: producto actualizado correctamente en nuestra DB
          content:
            application/json:
              schema:
                $ref: "#/components/requestBodies/updateProduct"
        "404":
          description: Producto no encontrado en la DB
        "500":
          description: Error interno del servidor, generalmente causado por una query defectuosa o fallo en la conexión.
    delete:
      summary: Elimina un producto según el pid (identificador del producto ObjectId)
      tags:
        - products
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto a eliminar
          schema:
            type: string
        - name: cookie
          in: header
          required: true
          description: JWT Cookie para autenticación
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado correctamente de nuestra DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/products"
        "404":
          description: Producto no encontrado en la DB
        "500":
          description: Error interno del servidor, generalmente causado por una query defectuosa o fallo en la conexión.

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: cookie
      name: JWT
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Titulo / Nombre del producto
        description:
          type: string
          description: Descripcion breve del producto
        code:
          type: string
          description: Código de identficacion del modelo
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad de producto en stock
        category:
          type: string
          description: Categoria a la que pertenece el producto
      example:
        title: Producto ejemplo actualizado
        description: Descripcion del producto actualizado
        code: CODER5575actualizado
        price: 150
        stock: 50
        category: Tech
  schemas:
    products:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado por MongoDb, id del producto
        title:
          type: string
          required: true
          description: Titulo / Nombre del producto
        description:
          type: string
          required: true
          description: Descripcion breve del producto
        code:
          type: string
          required: true
          unique: true
          description: Código de identficacion del modelo
        price:
          type: number
          required: true
          description: Precio del producto
        stock:
          type: number
          required: true
          description: Cantidad de producto en stock
        category:
          type: string
          required: true
          description: Categoria a la que pertenece el producto
      example:
        _id: 6019b0a7cf1c9a0e98efbc97
        title: Producto ejemplo
        description: Descripcion del producto
        code: CODER5575
        price: 99.99
        stock: 100
        category: Tech
